# Generated by Django 6.0 on 2026-04-22 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labor", "0004_payment_manager_alter_payment_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
