# Generated by Django 6.0 on 2026-03-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_name", models.CharField(max_length=200)),
                ("plant_count", models.IntegerField()),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="estates.estate",
                    ),
                ),
            ],
        ),
    ]
