# Generated by Django 6.0 on 2026-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
