# Generated by Django 6.0 on 2026-04-22 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_taskassignment_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="task_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
