# Generated by Django 6.0 on 2026-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estate_name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Total area in acres", max_digits=10
                    ),
                ),
            ],
        ),
    ]
