# Generated by Django 6.0 on 2026-03-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harvest_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity in kg", max_digits=10
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_records",
                        to="plots.plot",
                    ),
                ),
            ],
        ),
    ]
