# Generated by Django 6.0 on 2026-04-22 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="harvest_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
